# -*- coding: utf-8 -*-
"""markov chain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/126dRWIapSuphRvV_iqg9kBoQmKFdaecK
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive', force_remount= True)
# %cd /gdrive/MyDrive/'Colab Notebooks'/

import functions as f
from Text import *
from Chain_class import *

path = 'nietzsche.txt'
input_text = f.read_txt(path)

text = Text(input_text)
print(text.tokens[:15])
print(text.tokens_ind[:15])

chain_model = Chain(text, n=3)
chain_model.tokens_info()
chain_model.ngrams_info()

chain_model.transition_matrix_prob[1500,1200:1300].todense()

prefixes = ['truth is a', 'Truthfulness is ', 'Life is ,']
temperatures = [1, 0.7, 0.4, 0.1]
for temperature in temperatures:
    print('temperature:', temperature)
    print(chain_model.generate_sequence(np.random.choice(prefixes), 50, temperature=temperature))
    print('\n')

